# Generated by Django 4.2.11 on 2024-04-07 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image_Register_Users_Info",
        ),
    ]
