# Generated by Django 4.2.11 on 2024-04-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_delete_image_register_users_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image_Register_Users_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.TextField()),
                ("email", models.TextField()),
                ("verify_number", models.IntegerField()),
                ("expire_time", models.TextField()),
                ("cookie", models.TextField()),
                ("private_key", models.TextField()),
            ],
        ),
    ]
