# Generated by Django 4.2.11 on 2024-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_image_register_users_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image_register_users_info",
            name="account",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="image_register_users_info",
            name="email",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="image_register_users_info",
            name="verify_number",
            field=models.IntegerField(blank=True),
        ),
    ]
