# Generated by Django 4.2.11 on 2024-04-09 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_alter_image_register_users_info_account_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image_users_info",
            old_name="account_md5",
            new_name="account_sha256",
        ),
        migrations.RenameField(
            model_name="image_users_info",
            old_name="password_md5",
            new_name="password_sha256",
        ),
    ]
