# Generated by Django 4.2.11 on 2024-04-09 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0005_rename_account_md5_image_users_info_account_sha256_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image_register_users_info",
            name="private_key",
        ),
    ]
