# Generated by Django 4.2.11 on 2024-04-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0006_remove_image_register_users_info_private_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="image_register_users_info",
            name="pub_key",
            field=models.TextField(blank=True, default=None),
        ),
    ]
