# Generated by Django 4.2.11 on 2024-04-10 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0007_image_register_users_info_pub_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image_register_users_info",
            name="cookie",
        ),
    ]
