# Generated by Django 4.2.11 on 2024-04-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0008_remove_image_register_users_info_cookie"),
    ]

    operations = [
        migrations.AddField(
            model_name="image_register_users_info",
            name="pri_key",
            field=models.TextField(blank=True, default=None),
        ),
    ]
