# Generated by Django 4.2.11 on 2024-04-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0009_image_register_users_info_pri_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="image_users_info",
            name="pri_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="image_users_info",
            name="pub_key",
            field=models.TextField(blank=True),
        ),
    ]
