# Generated by Django 4.2.11 on 2024-04-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0010_image_users_info_pri_key_image_users_info_pub_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="image_users_info",
            name="sign_in_expire_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
