# Generated by Django 4.2.11 on 2024-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0011_image_users_info_sign_in_expire_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="image_users_info",
            name="is_login",
            field=models.BooleanField(default=False),
        ),
    ]
