# Generated by Django 4.2.11 on 2024-04-13 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0012_image_users_info_is_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image_users_info",
            name="is_login",
        ),
    ]
