# Generated by Django 4.2.11 on 2024-05-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0014_faces_to_images_info_images_to_faces_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="images_to_faces_info",
            name="landmarks",
            field=models.BooleanField(default=False),
        ),
    ]
