# Generated by Django 4.2.11 on 2024-05-25 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0015_images_to_faces_info_landmarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faces_to_images_info",
            name="face_weight",
        ),
        migrations.RemoveField(
            model_name="faces_to_images_info",
            name="total_face_matrix",
        ),
    ]
