# Generated by Django 4.2.11 on 2024-05-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0016_remove_faces_to_images_info_face_weight_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="History_Details_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_sha256", models.TextField()),
                ("target_image_id", models.IntegerField()),
                ("selected_faces_index_list", models.BinaryField()),
                ("pre_recognition_over_threshold", models.BinaryField()),
                ("pre_recognition_under_threshold", models.BinaryField()),
                ("submit_time", models.DateTimeField()),
            ],
        ),
    ]
