# Generated by Django 4.2.11 on 2024-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0017_history_details_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="image_users_info",
            name="threshold",
            field=models.FloatField(default=0.45),
        ),
        migrations.AlterField(
            model_name="history_details_info",
            name="submit_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
